data_dir: "/kaggle/working/DESC_MOL-DDIE/sample/tsv"
model_type: "bert"
model_name_or_path: "microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract"
task_name: "MRPC"
output_dir: "./output_dir"
config_name: ""
tokenizer_name: ""
cache_dir: ""
max_seq_length: 128
do_train: True
do_eval: True
evaluate_during_training: True
do_lower_case: True
per_gpu_train_batch_size: 32
per_gpu_eval_batch_size: 32
gradient_accumulation_steps: 1
learning_rate: 5.0e-5
weight_decay: 0.01
adam_epsilon: 1.0e-8
max_grad_norm: 1.0
num_train_epochs: 30.0
max_steps: -1
warmup_steps: 0
logging_steps: 10000
save_steps: 10000
eval_all_checkpoints: False
no_cuda: False
overwrite_output_dir: True
overwrite_cache: False
seed: 42
tpu: False
tpu_ip_address: ""
tpu_name: ""
xrt_tpu_config: ""
fp16: False
fp16_opt_level: "O1"
local_rank: -1
server_ip: ""
server_port: ""
parameter_averaging: False
dropout_prob: 0.1
middle_layer_size: 0
use_cnn: True
conv_window_size:
  - 5
pos_emb_dim: 10
activation: "gelu"
use_desc: False
desc_max_seq_length: 128
desc_conv_window_size: null
desc_conv_output_size: null
desc_layer_hidden: 0
use_mol: False
fingerprint_dir: ""
molecular_vector_size: null
gnn_layer_hidden: null
gnn_layer_output: null
gnn_mode: "sum"
gnn_activation: "gelu"
pretrained_dir: ""
pretrained_gnn_dir: null
pretrained_desc_dir: null
freeze_pretrained_parameters: False
feature_train_pt_path: "/teamspace/studios/this_studio/DDI-Multimodals-Fusion/data_test.pt"
feature_test_pt_path: "/teamspace/studios/this_studio/DDI-Multimodals-Fusion/data_train.pt"
device: "cuda"